<a href="https://colab.research.google.com/github/NirmalaMangamuri/ICP-3/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# 1. Create random vector
vec = np.random.randint(1, 21, size=15)

# 2. Reshape to 3x5
reshaped_vec = vec.reshape(3, 5)

# 3. Print shape
print("Shape of array:", reshaped_vec.shape)

# 4. Replace max in each row with 0
for i in range(reshaped_vec.shape[0]):
    max_index = reshaped_vec[i].argmax()
    reshaped_vec[i][max_index] = 0

print("Modified array:\n", reshaped_vec)

Shape of array: (3, 5)
Modified array:
 [[ 1  6 11  0 14]
 [ 0 13 15 11  3]
 [ 0 14 12  8 11]]


In [ ]:
# Create 4x3 array of 4-byte integers
arr = np.zeros((4, 3), dtype=np.int32)

print("Array:\n", arr)
print("Shape:", arr.shape)
print("Type:", type(arr))
print("Data type:", arr.dtype)

Array:
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
Shape: (4, 3)
Type: <class 'numpy.ndarray'>
Data type: int32


In [ ]:
# Define the array
matrix = np.array([[3, -2],
                   [1,  0]])

# Compute eigenvalues and right eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [2. 1.]
Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [ ]:
import numpy as np

# Define the array
arr = np.array([[0, 1, 2],
                [3, 4, 5]])

# Compute the sum of the main diagonal
diagonal_sum = np.trace(arr)

print("Sum of diagonal elements:", diagonal_sum)


Sum of diagonal elements: 4


In [ ]:
# Original 3x2 array
original_array = np.array([[1, 2],
                           [3, 4],
                           [5, 6]])

# Reshape to 2x3
reshaped_array = original_array.reshape(2, 3)

print("Reshaped 2x3 array:\n", reshaped_array)


Reshaped 2x3 array:
 [[1 2 3]
 [4 5 6]]
